version: 2.1

commands:
  install_dependencies:
    description: "Install project dependencies"
    steps:
      - run:
          name: Install Dependencies
          command: |
            npm install



executors:
  node-executor:
    docker:
      - image: circleci/node:14


jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - install_dependencies
      - persist_to_workspace:
          paths: 
            - project
          root: ~/
      - run : 
          name: Verify Installation
          command: |
            pwd

workflows:
  version: 2
  install_and_test:
    jobs:
      - install