version: 2.1

parameters:
  node-version:
    type: string
    default: "16.20.0"

commands:
  install-deps:
    description: "Install npm dependencies"
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - install-deps
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: ls -la

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20.0
    working_directory: ./house/node-backed

workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
